### ISSUE TITLE
Unable to launch and then crushes after discovering plugins

### ISSUE THREAD

**Issue by scout4u** [SublimeText/Mote#4]
A strage behavior of ST. Tree of files doesn't apear after connecting. The ST is almost clean cause been newly installed.

**Comment by hyperturtle** [comment]
Can you clarify the issue? Which version of sublime text are you using?

**Comment by daevski** [comment]
I'm noticing (I think) the same issue. I am running Beta 2171 (very new) and I've installed Mote with Package Control, and updated the json with server info. In Sublime I do CTRL+SHIFT+P "Mote {enter} and select my server that I configured {enter} and nothing more happens. I do see in the bottom into bar that it is trying to connect, but after that message disappears, I'm not sure what I'm supposed to do. I then do CTRL+SHIFT+P "Mote" again and see a new View and Disconnect option, but neither do anything :(

Let me know if I can give any more details! PS-- does Putty need to be in the Mote plugin directory or anything? How does it know how to connect with Putty?

**Comment by hyperturtle** [comment]
Yeah you need to copy psftp.exe from  from PuTTY in the same folder as Mote. Try that and let me know how it goes. You can also pull open the debug console Ctrl+` for more debug info.

**Comment by daevski** [comment]
So, PuTTY, psftp and pageant are all in Mote/ and running "Mote" in sublimetext2 gets me this from Console (CTRL+`): 

Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\Mote.py", line 219, in run
  File ".\Mote.py", line 315, in psftp
  File ".\Mote.py", line 325, in untilprompt
IOError: [Errno 22] Invalid argument

My config with saved session (working in putty) "ssh-key" looks like:
{
    "daevski.info":{
        "connection_string": "ssh-key",
        "idle_recursive": true,
       "default_path": "public_html/websites/ForTheKids/"
    }, 
...
...

**Comment by jwthomp** [comment]
I'm seeing the same issue as daevski with the same install steps and have psftp.exe in the same directory as Mote.

**Comment by koraktor** [comment]
I got this too, and this seems to be the same issue as #2. Copying psftp didn't help.

**Comment by hyperturtle** [comment]
I think I found the issue. It was because it would erroneously quote the psftp connection string and cause psftp to not recognize the saved session name. I pushed a fix, let know if it works.

**Comment by daevski** [comment]
I can't be sure It's working. I don't understand how the plugin is supposed to work. Nothing appears to be happening when I select "Mote" "Browse" in palette, but maybe one of the other commenters here can troubleshoot with you. I've moved on to using SFTP plugin cause it's easier and seems more feature rich, but I also don't mean any disrespect in informing you of that. Good Luck to you all :)

**Comment by mtaheny** [comment]
I am having the same issue.  Anyone find a fix?

**Comment by scout4u** [comment]
Do you write to me?
No nodody fixed that as I suppose. I even don't know. I see russian ru-scite. It's the best. ever.

27.07.2012, 00:58, "mtaheny" reply@reply.github.com:

> I am having the same issue.  Anyone find a fix?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SublimeText/Mote/issues/4#issuecomment-7290135

## 

C уважением, Бельков Андрей

**Comment by daevski** [comment]
Just use SFTP. I have a video that talks about it here: http://youtu.be/-On81uYhdr0

**Comment by scout4u** [comment]
Maybe. Thanks. That suks in editing. It can not highlight matching brackets and show dotted border between a pair and much more. I like ru-scite. In linux there is a close relative to scite — geany.

27.07.2012, 01:03, "daevski" reply@reply.github.com:

> Just use SFTP. I have a video that talks about it here: http://youtu.be/-On81uYhdr0
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SublimeText/Mote/issues/4#issuecomment-7290294

## 

C уважением, Бельков Андрей

**Comment by mtaheny** [comment]
Thanks for the quick reply does sftp support working behind a corp proxy? 
-----Original Message-----

**Comment by scout4u** [comment]
Maybe. It depends on configs :)
On level of toughness of sysadmin

27.07.2012, 01:27, "mtaheny" reply@reply.github.com:

> Thanks for the quick reply does sftp support working behind a corp proxy?
> -----Original Message-----
> From: daevski [mailto:reply@reply.github.com]
> Sent: Thursday, July 26, 2012 4:04 PM
> To: Taheny Mike (dec1mrt)
> Subject: Re: [Mote] Unable to launch and then crushes after discovering plugins (#4)
> 
> Just use SFTP. I have a video that talks about it here: http://youtu.be/-On81uYhdr0
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SublimeText/Mote/issues/4#issuecomment-7290294
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SublimeText/Mote/issues/4#issuecomment-7290992

## 

C уважением, Бельков Андрей

**Comment by daevski** [comment]
SFTP uses putty's psftp.exe, but first you might want to check the developers page about the plugin. Not sure it he has config for proxies... http://bit.ly/q38wBs

**Comment by mtaheny** [comment]
Awesome, got it.  The psftp setting tipped me off.  That is what Mote was using.  Thanks for the help.

-----Original Message-----
